prepare:
    fetch:
        -
            url: 'https://raw.githubusercontent.com/iakunin/codestyle/0.0.6/.editorconfig'
            path: '.editorconfig'
        -
            url: 'https://raw.githubusercontent.com/iakunin/codestyle/0.0.6/java/checkstyle.xml'
            path: 'var/codestyle/checkstyle.xml'

plugins:
    markdownlint:
        enabled: true
        issue_override:
            severity: minor
    editorconfig:
        enabled: true
        issue_override:
            severity: minor
    checkstyle:
        enabled: true
        config: 'var/codestyle/checkstyle.xml'

exclude_patterns:
    - "/.gradle/"
    - "/.idea/"
    - "/build/"
    - "/out/"
    - "/gradlew"
    - "/gradlew.bat"
    - "**/*.jar"
