prepare:
    fetch:
        -
            url: 'https://raw.githubusercontent.com/iakunin/codestyle/0.0.13/.editorconfig'
            path: '.editorconfig'
        -
            url: 'https://raw.githubusercontent.com/iakunin/codestyle/0.0.13/java/checkstyle.xml'
            path: 'var/codestyle/checkstyle.xml'
        -
            url: 'https://raw.githubusercontent.com/iakunin/codestyle/0.0.13/java/pmd.xml'
            path: 'var/codestyle/pmd.xml'
        -
            url: 'https://raw.githubusercontent.com/iakunin/codestyle/0.0.13/markdown/.mdl-rules.rb'
            path: '.mdl-rules.rb'
        -
            url: 'https://raw.githubusercontent.com/iakunin/codestyle/0.0.13/markdown/.mdlrc'
            path: '.mdlrc'

checks:
    file-lines:
        config:
            threshold: 1000

plugins:
    markdownlint:
        enabled: true
        issue_override:
            severity: minor
    editorconfig:
        enabled: true
        issue_override:
            severity: minor
    checkstyle:
        enabled: true
        config: 'var/codestyle/checkstyle.xml'
    pmd:
        enabled: true
        config: 'var/codestyle/pmd.xml'

exclude_patterns:
    - '/.gradle/'
    - '/.idea/'
    - '/build/'
    - '/out/'
    - '/gradlew'
    - '/gradlew.bat'
    - '**/*.jar'
