extends: default

rules:
    braces:
        min-spaces-inside: 0
        max-spaces-inside: 1
        min-spaces-inside-empty: 0
        max-spaces-inside-empty: 0
    brackets:
        min-spaces-inside: 0
        max-spaces-inside: 1
        min-spaces-inside-empty: 0
        max-spaces-inside-empty: 0
    colons:
        max-spaces-before: 0
        max-spaces-after: 1
    commas:
        max-spaces-before: 0
        min-spaces-after: 1
        max-spaces-after: 1
    comments:
        require-starting-space: true
        min-spaces-from-content: 1
    document-end:
        present: false
    document-start:
        present: false
    empty-lines:
        max: 1
        max-start: 0
    empty-values:
        forbid-in-block-mappings: true
        forbid-in-flow-mappings: true
    hyphens:
        max-spaces-after: 1
    indentation:
        spaces: 4
        indent-sequences: true
        check-multi-line-strings: true
    line-length:
        max: 80
    new-lines:
        type: unix
    octal-values:
        forbid-implicit-octal: true
    quoted-strings:
        quote-type: single
        required: only-when-needed
