version: '3.7'

services:
    db:
        container_name: codexia-bot-db
        image: postgres:11.5
        restart: always
        environment:
            POSTGRES_DB: codexia-bot
            POSTGRES_USER: codexia-bot
            POSTGRES_PASSWORD: codexia-bot
        ports:
            - 54322:5432
        volumes:
            - ./var/postgresql/data:/var/lib/postgresql/data

    zookeeper:
        container_name: codexia-bot-zookeeper
        image: wurstmeister/zookeeper:3.4.6
        ports:
            - 2181:2181
        volumes:
            - ./var/zookeeper:/opt/zookeeper-3.4.6/data

    kafka:
        container_name: codexia-bot-kafka
        image: wurstmeister/kafka:2.12-2.4.0
        ports:
            - 9092:9092
        expose:
            - 9093
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
            KAFKA_CREATE_TOPICS: "hackernews_item:1:1,github_repo:1:1,demo-topic:1:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./var/kafka:/kafka
