version: 2
jobs:
    build:
        docker:
            - image: gradle:6.0.1-jdk11
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - gradle-dependencies-v1-{{ checksum "build.gradle" }}
                      # fallback to using the latest cache if no exact match is found
                      - gradle-dependencies-v1-
            - run:
                name: gradle-dependencies
                command: gradle dependencies
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-dependencies-v1-{{ checksum "build.gradle" }}
            - run:
                  name: gradle-build
                  command: gradle clean build --info
