version: 2.1
orbs:
    gcr: circleci/gcp-gcr@0.6.1
    gke: circleci/gcp-gke@1.0.3
jobs:
    build-jar:
        docker:
            -   image: gradle:6.0.1-jdk11
        steps:
            - checkout
            -   restore_cache:
                    keys:
                        - gradle-dependencies-v1-{{ checksum "build.gradle" }}
                        # fallback to using the latest cache if no exact match is found
                        - gradle-dependencies-v1-
            -   run:
                    name: gradle-dependencies
                    command: gradle dependencies
            -   save_cache:
                    paths:
                        - ~/.gradle
                    key: gradle-dependencies-v1-{{ checksum "build.gradle" }}
            -   run:
                    name: gradle-build
                    command: gradle clean build --info
            -   persist_to_workspace:
                    root: .
                    paths:
                        - build/*
    build-and-push-image:
        description: Build and push image to Google Container Registry
        machine: true
        steps:
            - checkout
            -   attach_workspace:
                    at: /tmp/workspace
            -   run:
                    name: copy-artifacts-from-workspace
                    command: cp -r /tmp/workspace/build .
            - gcr/gcr-auth
            -   gcr/build-image:
                    image: backend
                    registry-url: eu.gcr.io
                    tag: $CIRCLE_SHA1
            -   gcr/push-image:
                    image: backend
                    registry-url: eu.gcr.io
                    tag: $CIRCLE_SHA1
    rollout-image:
        description: Deploy application to Google Kubernetes Engine
        machine: true
        steps:
            - gke/install
            -   gke/update-kubeconfig-with-credentials:
                    cluster: standard-cluster-1
                    install-kubectl: true
                    perform-login: true
            -   gke/rollout-image:
                    cluster: standard-cluster-1
                    container: backend
                    deployment: backend-deployment
                    image: eu.gcr.io/$GOOGLE_PROJECT_ID/backend
                    namespace: codexia-bot
                    tag: 0dff20f1385c5fa0fcb4707e61c934344e45b033
workflows:
    build_update_deploy:
        jobs:
            - rollout-image
#            - build-jar
#            -   build-and-push-image:
#                    requires:
#                        - build-jar
#            #                    filters:
#            #                        tags:
#            #                            only: /^\d+.\d+.\d+$/
#            -   rollout-image:
#                    requires:
#                        - build-and-push-image

