version: 2.1
orbs:
    gcr: circleci/gcp-gcr@0.6.1
    gke: circleci/gcp-gke@1.0.3
jobs:
    build-jar:
        docker:
            -   image: gradle:6.0.1-jdk11
        steps:
            - checkout
            -   restore_cache:
                    keys:
                        - gradle-dependencies-v1-{{ checksum "build.gradle" }}
            -   run:
                    name: gradle-build
                    command: gradle clean -Pversion=$CIRCLE_TAG build sonarqube --info
            -   save_cache:
                    paths:
                        - ~/.gradle
                    key: gradle-dependencies-v1-{{ checksum "build.gradle" }}
            -   persist_to_workspace:
                    root: .
                    paths:
                        - build/*
    build-and-push-image:
        description: Build and push image to Google Container Registry
        machine: true
        steps:
            - checkout
            -   attach_workspace:
                    at: /tmp/workspace
            -   run:
                    name: copy-artifacts-from-workspace
                    command: cp -r /tmp/workspace/build .
            - gcr/gcr-auth
            -   gcr/build-image:
                    image: backend
                    registry-url: eu.gcr.io
                    tag: $CIRCLE_TAG
            -   gcr/push-image:
                    image: backend
                    registry-url: eu.gcr.io
                    tag: $CIRCLE_TAG
    rollout-image:
        description: Deploy application to Google Kubernetes Engine
        machine: true
        steps:
            - gke/install
            -   gke/update-kubeconfig-with-credentials:
                    cluster: standard-cluster-1
                    perform-login: true
            -   gke/rollout-image:
                    cluster: standard-cluster-1
                    container: backend
                    deployment: backend-deployment
                    image: eu.gcr.io/$GOOGLE_PROJECT_ID/backend
                    namespace: codexia-bot
                    tag: $CIRCLE_TAG
workflows:
    main:
        jobs:
            -   build-jar:
                    context: SonarCloud
                    filters:
                        tags:
                            only: /^\d+\.\d+\.\d+$/
#            -   build-and-push-image:
#                    requires:
#                        - build-jar
#                    filters:
#                        branches:
#                            ignore: /.*/
#                        tags:
#                            only: /^\d+\.\d+\.\d+$/
#            -   rollout-image:
#                    requires:
#                        - build-and-push-image
#                    filters:
#                        branches:
#                            ignore: /.*/
#                        tags:
#                            only: /^\d+\.\d+\.\d+$/
